// ConstraintLoader.cs — Auto-configures physics from JSON manifest.
// Drop on root GameObject, assign manifest, press Play.
using UnityEngine;

public class ConstraintLoader : MonoBehaviour {
    public TextAsset manifestFile;
    // Full implementation: reads manifest JSON, creates ConfigurableJoints,
    // applies drive_ratios, collision bounds, and COM offset.
    // Generated by Trench-Builder Pipeline.
}
